### ISSUE TITLE
Site can't be reached via localhost:8787 

### ISSUE THREAD

**Issue by HEsiyun** [dorianps/docker#2]
Hi, 

I'm trying to run the container on Windows 10 Pro. I have no problem with running the container and log in to RStudio when choosing not to mount a Windows folder in the container. But if I choose to mount a local folder, I will be redirected to http://localhost:8787/ and not able to login to RStudio. 

Any ideas?

Thanks,
Siyun

**Comment by dorianps** [comment]
Have you given access to share that drive in docker settings? It is not enabled by default.

My next guess is the firewall, which in my case used to prevent the sharing from happening because it was blocking local access to port 445. When docker was trying to get access for the shared drive it would not succeed (i.e., when you enable it in settings). If that is the case, you can try disabling the antivirus, firewall, etc.

**Comment by dorianps** [comment]
Also, check and report the error messages in the terminal, it might tell you what is going on.

**Comment by HEsiyun** [comment]
Hi,

Thanks for the explanation. The problem solved when I was given access to share that drive in docker settings. 

Best,
Siyun
